force-app/main/default/objects/AssetIncrementManager__mdt/AssetIncrementManager__mdt.object-meta.xml
<CustomObject>
    <label>Asset Increment Manager</label>
    <pluralLabel>Assets Increment Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/AssetIncrementManager__mdt/fields/AssetIncrementCounter__c.field-meta.xml
<CustomField>
    <fullName>AssetIncrementCounter__c</fullName>
    <label>Asset Increment Counter</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AssetPrefixMapping__mdt/AssetPrefixMapping__mdt.object-meta.xml
<CustomObject>
    <label>Asset Prefix Mapping</label>
    <pluralLabel>Asset Prefix Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AssetPrefixMapping__mdt/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GC</fullName>
                <default>true</default>
                <label>GC</label>
            </value>
            <value>
                <fullName>CPU</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssetPrefixMapping__mdt/fields/RecordTypeDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeDeveloperName__c</fullName>
    <label>Record Type Developer Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Graphic_Card</fullName>
                <default>true</default>
                <label>Graphic_Card</label>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Motherboard</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetTriggerHelper.cls
public with sharing class AssetTriggerHelper {
    static String ASSET_SOBJECT_TYPE = 'Asset';
    static List<Asset> currentAssets;
    
    public static void generateAssetExternalId(Set<Id> assetIds){
        List<Asset> assets = [SELECT ID, RecordTypeId, ProductCode FROM Asset WHERE ID in :assetIds];
        List<Asset> assetsToUpdate = new List<Asset>();
        Map<String, String> assetRTPrefixMap = new Map<String, String>();
        Map<String, Decimal> assetIncrementMap = new Map<String, Decimal>();
        Map<ID, String> productRTMap = new Map<Id, String>();
        Map<ID, String> productCodeMap = new Map<Id, String>();
        // map asset record types
        for(RecordType RT: [SELECT ID, Name, DeveloperName, SobjectType FROM RecordType WHERE SobjectType =:ASSET_SOBJECT_TYPE]){
            productRTMap.put(RT.ID, RT.DeveloperName);
        }
        //get increment map mdt
        for(AssetIncrementManager__mdt incManager : [SELECT Asset_Identifier__c, AssetIncrementCounter__c FROM AssetIncrementManager__mdt]){
            assetIncrementMap.put(incManager.Asset_Identifier__c, incManager.AssetIncrementCounter__c);
        }
        //get Asset Record Prefix map mdt
        for(AssetPrefixMapping__mdt assetPrefMap: [SELECT Prefix__c, RecordTypeDeveloperName__c FROM AssetPrefixMapping__mdt]){
            assetRTPrefixMap.put(assetPrefMap.RecordTypeDeveloperName__c, assetPrefMap.Prefix__c);
        }
        // generate external id
        for(Asset assetElement: assets){
            Asset assetToUpdate = new Asset();
            assetToUpdate.Id = assetElement.Id;
            String assetIdentifier = assetRTPrefixMap.get(productRTMap.get(assetElement.RecordTypeId)) + '-' + assetElement.ProductCode;
            String newAssetIdentifier;
            if(assetIncrementMap != null && assetIncrementMap.keySet() != null && assetIncrementMap.keySet().contains(assetIdentifier)){
                newAssetIdentifier = assetIdentifier + '-' + UtilityClass.formatInteger(assetIncrementMap.get(assetIdentifier));
                //increment
                assetIncrementMap.put(assetIdentifier, assetIncrementMap.get(assetIdentifier) + 1);
            }else{
                assetIncrementMap.put(assetIdentifier, 1);
                newAssetIdentifier = assetIdentifier  + '-0000';
            }
        }
        //update increment metadata
        List<Map<String, Object>> mapTestDataLst = new List<Map<String, Object>>();
        for(String incManager : assetIncrementMap.keySet()){
            Map<String, Object> mapTestData = new Map<String, Object>();
            mapTestData.put('Asset_Identifier__c', incManager);
            mapTestData.put('label', incManager);
            mapTestData.put('AssetIncrementCounter__c', assetIncrementMap.get(incManager));
            mapTestDataLst.add(mapTestData);
        }
        metadataInsertUpdate.handleInsertAndUpdate(mapTestDataLst);
        //updateAssets();
    }
}